name: "Bug or Feedback"
description: "Report a bug or share feedback"
labels: ["feedback"]
body:
  - type: dropdown
    id: type
    attributes:
      label: "Type"
      description: "Is this a bug or general feedback?"
      options:
        - Bug
        - Feedback
      default: 0
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How bad is it?"
      options:
        - Critical (blocks use)
        - Major (painful workaround)
        - Minor (cosmetic/usability)
      default: 1
    validations:
      required: true
  - type: input
    id: summary
    attributes:
      label: "Summary"
      placeholder: "Short title of the issue"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected"
      placeholder: "What you expected to happen"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "Actual"
      placeholder: "What actually happened"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      placeholder: "1. Go to ...\n2. Click ...\n3. Observe ..."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      placeholder: "OS, browser/app version, platform details"
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: "Screenshots / logs"
      description: "Paste links or drag-and-drop images"
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: "Contact (optional)"
      placeholder: "Handle or email if follow-up is OK"
    validations:
      required: false
